name: Decrypt and Generate File

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  decrypt:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      
      - name: Initialize submodules
        run: |
          git submodule update --init --recursive
          ls -la url-decrypt-service/  # 检查子模块内容
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests cryptography
          
      - name: Run decryption script
        run: |
          pwd
          ls -la
          python -c "import sys; print(sys.path)"
          python decrypt_script.py
        
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output.txt
          git commit -m "Update decrypted content" -a || exit 0
          git push 