name   名字: Generate Token and Encrypted URL

on:   :
  push:   推动:
    branches:   分支:
      - main   ——主要

jobs:   工作:
  generate-token:
    runs-on: ubuntu-latest   运行环境：Ubuntu最新版本
    steps:   步骤:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Token
        run: |
          TOKEN=$(uuidgen)
          echo "TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Generate Encrypted URL
        run: |
          ENCRYPTED_URL="http://your_domain.com/live?token=${{ env.TOKEN }}"
          echo "ENCRYPTED_URL=$ENCRYPTED_URL" >> $GITHUB_ENV

      - name: Store Encrypted URL
        run: |
          echo "${{ env.ENCRYPTED_URL }}" > encrypted_url.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add encrypted_url.txt
          git commit -m "Update encrypted URL"
          git push   git推

