# 工作流名称：生成令牌和加密URL
name: Generate Token and Encrypted URL

# 触发条件：当代码推送到main分支时
on:
  push:
    branches:
      - main

jobs:
  # 定义任务：生成令牌
  generate-token:
    # 指定运行环境为最新版本的Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 步骤1：检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 步骤2：生成唯一令牌
      # 使用uuidgen命令生成UUID作为令牌，并将其存储在GitHub Actions的环境变量中
      - name: Generate Token
        run: |
          TOKEN=$(uuidgen)
          echo "TOKEN=$TOKEN" >> $GITHUB_ENV

      # 步骤3：生成加密URL
      - name: Generate Encrypted URL
        run: |
          # 使用GitHub Secrets中存储的直播源URL
          ENCODED_STREAM=$(echo -n "${{ secrets.STREAM_URL }}" | base64)
          ENCRYPTED_URL="https://your_github_username.github.io/your_repo_name/live.html?token=${{ env.TOKEN }}&stream=$ENCODED_STREAM"
          echo "ENCRYPTED_URL=$ENCRYPTED_URL" >> $GITHUB_ENV

      # 步骤4：保存加密URL到仓库
      # 将生成的URL保存到文件中，并通过git提交更改
      - name: Store Encrypted URL
        run: |
          # 将加密URL写入文件
          echo "${{ env.ENCRYPTED_URL }}" > encrypted_url.txt
          # 配置git提交信息
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # 添加文件到git
          git add encrypted_url.txt
          # 提交更改
          git commit -m "Update encrypted URL"
          # 推送到远程仓库
          git push