name: Update IPTV Sources

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:      # 允许手动触发

jobs:
  update-iptv:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # 添加写入权限
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # 使用 GITHUB_TOKEN
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
    
    - name: Run crawler
      run: |
        ls -la  # 调试：列出当前目录内容
        python crawler.py
    
    - name: Commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # 检查并添加存在的文件
        for file in iptv.m3u iptv_ipv4.m3u iptv_ipv6.m3u iptv_both.m3u iptv.txt iptv_ipv4.txt iptv_ipv6.txt iptv_both.txt; do
          if [ -f "$file" ]; then
            git add "$file"
          fi
        done
        
        # 检查是否有文件要提交
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update IPTV sources $(date +'%Y-%m-%d')"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 设置环境变量